config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'dashboard', to: 'dashboard#index', as: 'dashboard'
  get '/@:username', to: 'account#show', as: 'profile'
  get '/@:username/follow', to: 'follows#follow', as: 'follow'
  get '/@:username/unfollow', to: 'follows#unfollow', as: 'unfollow'

  # Account Devise
  devise_for :users,
    path: 'account',
    controllers: {
      registrations: 'account/registrations',
      sessions: "account/sessions"
    },
    path_names: {
      sign_up: 'sign-up',
      sign_in: 'sign-in',
      sign_out: 'sign-out',
      password: 'password',
      confirmation: 'verify',
      edit: 'settings'
    }
  resources :news
  get '/news/:id/destroy', to: 'news#destroy', as: 'destroy_news'


  resources :tags
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :recoverable, :rememberable,
         :trackable, :validatable, :confirmable, authentication_keys: [:login]
  acts_as_birthday :birthday
  acts_as_followable
  acts_as_follower
  acts_as_tagger

  has_enumeration_for :gender, with: Gender, create_helpers: true
  has_enumeration_for :role, with: UserRole, create_helpers: true, create_scopes: true

  before_validation :default_values, :normalize_values

  validates :name, length: { maximum: 50 }, full_name: true, allow_blank: true
  validates :username, presence: true, uniqueness: { case_sensitive: false }, username: true, length: { in: 2..50 }
  validates :password, presence: true, on: :update, allow_blank: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }, length: { in: 5..50 }
  validates :gender, presence: true
  validates :role, presence: true
  validates :birthday, allow_blank: true, date: { after: 100.years.ago, before: 01.years.ago }
  validates :description, length: { maximum: 500 }

  attr_accessor :login

  def age
    birthday_age
  end

  def activities
    PublicActivity::Activity.where(owner_id: self.id).order(created_at: :desc)
  end

  def follows_activities
    PublicActivity::Activity.where(owner_id: self.follows.map(&:followable_id)).order(created_at: :desc)
  end

  private

  def default_values
    self.gender ||= Gender::OTHER
    self.role ||= UserRole::REGULAR
  end

  def normalize_values
    self.email = email.downcase if email.present?
  end

  # Devise: e-mail or username to sign-in - https://github.com/freaktags/core/issues/48
  def self.find_for_database_authentication(conditions = {})
    find_by(username: conditions[:login]) || find_by(email: conditions[:login])
  end

  def devise_mailer
    DeviseCustomMailer
  end
end

app/views/users/_friends_tab.html.erb
<br>
<% friends.each do |f| %>
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="well well-sm">
        <div class="media">
          <%= link_to gravatar_for(f, class: "img-circle pull-left"), profile_path(f.username) %>
          <div class="media-body" >
            <div style="margin-left: 10px;">
              <h3 class="media-heading">
               <%= link_to f.username, profile_path(f.username) %>
              </h3>
              <div class="btn-group" role="group">
                <%= link_to fa("user-plus"), dashboard_path, title: :add.to_s.titleize, class: "btn btn-default" %>
                <%= link_to fa("comment-o"), dashboard_path, title: :message.to_s.titleize, class: "btn btn-default" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/users/show.html.erb
<div class="row">
  <div class="col-sm-4">
    <%= gravatar_for(@user, class: "img-circle img-responsive pull-left") %>
    <div style="margin-left: 100px; margin-bottom: 20px;">
      <h2 ><%= @user.username %></h2>
      <div class="btn-group" role="group">
        <%= link_to fa("user-plus"), dashboard_path, title: :add.to_s.titleize, class: "btn btn-default" %>
        <%= link_to fa("comment-o"), dashboard_path, title: :message.to_s.titleize, class: "btn btn-default" %>
      </div>
    </div>

    <ul class="list-group">
      <li class="list-group-item text-muted">
        <%= fa('user', text: 'Profile') %>
      </li>
      <li class="list-group-item text-right">
        <span class="pull-left">
          <strong><%= t('Joined') %> </strong>
        </span>
        <%= datetime_ago @user.created_at %>
      </li>
      <li class="list-group-item text-right">
        <span class="pull-left">
          <strong><%= t('Last Seen') %></strong>
        </span>
        <%= datetime_ago @user.current_sign_in_at %>
      </li>
      <li class="list-group-item text-right">
        <span class="pull-left">
          <strong><%= t('Username') %></strong>
        </span>
        <%= @user.username %>
      </li>
    </ul>
  </div>
  <div class="col-sm-8">
    <ul class="nav nav-tabs" id="user-profile-tabs">
      <li class="active">
        <a href="#tab-user-activity" data-toggle="tab">
          <%= fa('rss', text: 'Activity') %>
        </a>
      </li>
      <li>
        <a href="#tab-user-friends" data-toggle="tab">
        <%= fa('users', text: 'Friends') %>
        </a>
      </li>
    </ul>

    <div class="tab-content">
      <div class="tab-pane active" id="tab-user-activity">
        <%= render 'public_activity/default', activities: @user.activities  %>
      </div>
      <div class="tab-pane " id="tab-user-friends">
        <%= render 'users/friends_tab', friends: @user.friends  %>
      </div>
  </div>
</div>