config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'dashboard', to: 'dashboard#index', as: 'dashboard'
  get '/@:username', to: 'account#show', as: 'profile'
  get '/@:username/follow', to: 'follows#follow', as: 'follow'
  get '/@:username/unfollow', to: 'follows#unfollow', as: 'unfollow'

  # Account Devise
  devise_for :users,
    path: 'account',
    controllers: {
      registrations: 'account/registrations',
      sessions: "account/sessions"
    },
    path_names: {
      sign_up: 'sign-up',
      sign_in: 'sign-in',
      sign_out: 'sign-out',
      password: 'password',
      confirmation: 'verify',
      edit: 'settings'
    }
  resources :news
  get '/news/:id/destroy', to: 'news#destroy', as: 'destroy_news'


  resources :tags
end

app/models/news.rb
class News < ActiveRecord::Base
  include FriendlyId
  include PublicActivity::Model
  tracked only: [:create], owner: :author

  acts_as_paranoid
  acts_as_taggable
  friendly_id :title

  belongs_to :author, class_name: "User"

  validates :title, presence: true, length: { in: 5..150 }
  validates :slug_line, presence: true, length: { in: 20..150 }
  validates :content, presence: true, length: { in: 1..100000 }
  validates :author, presence: true

  private

  def should_generate_new_friendly_id?
    title_changed?
  end

end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  load_and_authorize_resource

  def index
    @news = News.all.includes(:author).order(created_at: :desc)
  end

  def show

  end

  def new
    @news = News.new
  end

  def create
    @news = News.new(news_params)
    @news.author = current_user
    if @news.save
      redirect_to(@news, notice: t(:created_successfully))
    else
      render :new
    end
  end

  def update
    if @news.update(news_params)
      redirect_to(@news, notice: t(:updated_successfully))
    else
      render :edit
    end
  end

  def destroy
    @news.destroy
    redirect_to(news_index_path, notice: t(:destroyed_successfully))
  end

  private

  def news_params
    params.require(:news).permit(:title, :slug_line, :content, :tag_list)
  end
end

app/helpers/news_helper.rb
module NewsHelper

end

app/views/news/_form.html.erb
<%= form_for(@news) do |f| %>
  <% if @news.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@news.errors.count, "error") %> prohibited this from being saved:</h2>
      <ul>
      <% @news.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.text_field :title, class: 'input-title', placeholder: :title %>
  </div>
  <hr/>
  <div class="field">
    <%= f.text_field :slug_line, class: 'input-slugline', placeholder: :"Slug-line"  %>
  </div>
  <hr/>
  <div class="field">
    <%= f.text_field :tag_list, class: 'input-tags tags', value: @news.tag_list.sort.join(",")  %>
  </div>
  <hr/>
  <div class="field">
    <%= f.text_area :content, class: "html-editor medium-editor-textarea", placeholder: "Content" %>
  </div>
  <hr/>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/news/edit.html.erb
<%= render 'form' %>

app/views/news/index.html.erb
<h1><%= t :news %></h1>
<div class="btn-group btn-group-sm" role="group" style="  float: right;" aria-label="...">
  <%= link_to fa("plus", :text => t(:new)), new_news_path, class: "btn btn-success" if can? :create, @news %>
</div>
<hr>
<div>
<% @news.each do |news| %>
  <h2><%= link_to news.title, news %></h2>
  <% if news.created_at.present? %>
    <div class="info">
      <%= fa("calendar", text: t(:created)) %> <%= datetime_ago news.created_at %>
      | <%= fa("user") %> <%= link_to news.author.username, profile_path(news.author.username) %>
    </div>
  <% end %>
  <div class="slug-line"><%= news.slug_line %></div>
<% end %>
</div>
<p> <%= link_to "New", new_news_path %> </p>

app/views/news/new.html.erb
<%= render 'form' %>

app/views/news/show.html.erb
<h1> <%= @news.title %> </h1>
<div class="btn-group btn-group-sm" role="group" style="  float: right;" aria-label="...">
  <%= link_to fa("plus", :text => t(:new)), new_news_path, class: "btn btn-default" if can? :create, @news %>
  <%= link_to fa("wrench", :text => t(:edit)), edit_news_path(@news), class: "btn btn-default" if can? :update, @news %>
  <%= link_to fa("trash", :text => t(:destroy)), destroy_news_path(@news), class: "btn btn-default", "data-destroy": true, "data-destroy-message": content_tag(:h4, (t(:are_you_sure_destroy, title: content_tag(:u, @news.title)))) if can? :destroy, @news %>

</div>
<hr/>
<h5><i><%= @news.slug_line %></i></h5>
<hr>
<%= fa("calendar") %> <%= datetime_ago @news.created_at %>
| <%= fa("heart") %> 1000
| <%= fa("share") %> 350
| <%= fa("tags") %>

  <% @news.tags.each do |tag| %>
    <%= link_tag(tag) %>
  <% end %>
<hr>

<div class="row-fluid">
  <%= @news.content.html_safe %>
</div>