config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'dashboard', to: 'dashboard#index', as: 'dashboard'
  get '/@:username', to: 'account#show', as: 'profile'
  get '/@:username/follow', to: 'follows#follow', as: 'follow'
  get '/@:username/unfollow', to: 'follows#unfollow', as: 'unfollow'

  # Account Devise
  devise_for :users,
    path: 'account',
    controllers: {
      registrations: 'account/registrations',
      sessions: "account/sessions"
    },
    path_names: {
      sign_up: 'sign-up',
      sign_in: 'sign-in',
      sign_out: 'sign-out',
      password: 'password',
      confirmation: 'verify',
      edit: 'settings'
    }
  resources :news
  get '/news/:id/destroy', to: 'news#destroy', as: 'destroy_news'


  resources :tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include PublicActivity::StoreController
  protect_from_forgery with: :exception
  before_filter :authenticate_user!

  # Intercept exception behavior - https://github.com/freaktags/core/issues/107
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include FontAwesomeHelper
  include DatetimeAgoHelper
  include AccountHelper

  # TODO: Make it get a controller translated name
  def page_title
    title = t(:freaktags)
    if Rails.env.development?
      return "#{title} (#{FreakTags::Application::VERSION})"
    end
    title
  end

  def navbar_logo
    link_to (fa "tags", {text: t(:freaktags)}), (signed_in? ? dashboard_path : root_path), {:class => "navbar-brand logo"}
  end

  def navbar_left_logo
    link_to (fa "tags"), dashboard_path
  end
end

app/views/layouts/application/_constants.html.erb
<%= hidden_field_tag "freaktags-version", FreakTags::Application::VERSION %>
<%= hidden_field_tag "freaktags-locale", I18n.locale %>
<%= hidden_field_tag "freaktags-ga-id", ENV['FT_GA_ID'] %>

app/views/layouts/application/_flash.html.erb
<flash id="flash-messages">
  <% flash.each do |key, value| %>
    <% key = (key == 'alert') ? 'danger' : key %>
    <% key = (key == 'notice') ? 'info' : key %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
</flash>

app/views/layouts/application/_ga.html.erb
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', document.getElementById('freaktags-ga-id').value, 'auto');
  ga('send', 'pageview');
</script>

app/views/layouts/application/_navbar_left.html.erb
<% if signed_in? %>
  <nav id="navbar-left" class="col-lg-1 col-md-1 col-xs-1" >
    <center><%= link_to gravatar_for(current_user, class: "img-circle", id: "navbar-left-user-img"), current_user, title: current_user.username, "data-placement": "right" %></center>
    <hr/>
    <ul id="navbar-left-links"class="nav nav-stacked">
      <li><%= link_to fa("dashboard"), dashboard_path, title: :dashboard.to_s.titleize, "data-placement": "right" %></li>
      <li><%= link_to fa("newspaper-o"), news_index_path, title: :news.to_s.titleize, "data-placement": "right" %></li>
      <li><%= link_to fa("tags"), tags_path, title: :my_tags.to_s.titleize, "data-placement": "right" %></li>
      <% if Rails.env.development? %>
        <li><%= link_to fa("list"), news_index_path, title: :lists.to_s.titleize, "data-placement": "right" %></li>
      <% end %>
      <li><%= link_to fa("wrench"), edit_registration_path(:user), title: :account.to_s.titleize, "data-placement": "right" %></li>
      <li><%= link_to fa("sign-out"), destroy_session_path(:user), title: :"sign-out".to_s.titleize, "data-placement": "right" %></li>
    </ul>
  </nav>
<% end %>

app/views/layouts/application/_navbar_top.html.erb
<nav id="navbar-top" class="navbar navbar-default navbar-fixed-top">
 <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/"><%= fa "tags"%> <%= t :freaktags %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
      <% if signed_in? %>
      <ul class="nav navbar-nav hidden-xs">
        <li class="active"><a href="/dashboard"><%= fa("dashboard") %> Dashboard <span class="sr-only">(current)</span></a></li>
        <li><a href="/news"><%= fa("newspaper-o") %> News </a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <% end %>
      <ul class="nav navbar-nav navbar-right hidden-xs">
        <% if signed_in? %>
        	<li><a href="#">Link</a></li>
	        <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= gravatar_for(current_user, class: "img-circle navbar_user")%> <span class="caret"></span></a>
	          <ul class="dropdown-menu" role="menu">
	            <li><a href="/account/settings"><i class="fa fa-wrench"></i> Account Settings</a></li>
	            <li class="divider"></li>
	            <li><a href="/account/sign-out"><i class="fa fa-sign-out"></i>Sign Out</a></li>
	          </ul>
	        </li>
        <% end %>
      </ul>
  </div><!-- /.container-fluid -->
</nav>
<div class="navbar_top_fade">
</div>